name: deploy.yaml
on:
  push:
    branches:
      - main

jobs:
  deploy :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build -t yt-upload-worker:$NOW .
          docker tag yt-upload-worker:$NOW ytbackend.azurecr.io/yt-upload-worker:$NOW

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Push to ECR
        run: |
          az acr login --name ytbackend
          docker push ytbackend.azurecr.io/yt-upload-worker:$NOW

      - name: Download image on azure container app and deploy
        run: |
          az containerapp update \
            --name yt-upload-worker \
            --resource-group crushed-lemon-yt \
            --image ytbackend.azurecr.io/yt-upload-worker:$NOW
